; Edited by neil78@bilibili
; 注意，需要 32G 内存，才能使用这个配置文件 (Beware, 32GB RAM is required, if you choose use the code in this configuration file)
; Select the highest quality in settings, and you can choose from Performance, Balance, and Quality for AMD FSR settings
; Reference, https://github.com/AlteriaX/WuWa-Configs/blob/main/Config 2/Engine.ini
; Add the command below to fix stuttering with menus when using DLSS Frame Gen (Increases VRAM usage)

[Core.Log]
global=none
 
[SystemSettings]
AudioThread.AboveNormalPriority=1
AudioThread.EnableBatchProcessing=1
AudioThread.BatchAsyncBatchSize=128
AudioThread.UseBackgroundThreadPool=1

[/Script/Engine.RendererSettings]
r.StaticMeshLODDistanceScale=0.7
r.Kuro.KuroBloomStreak=0
r.SceneColorFringeQuality=0
r.AmbientOcclusionMaxQuality=100
r.Shadow.RadiusThreshold=0.03
r.Shadow.MaxCSMResolution=4096
r.Shadow.MinResolution=512
r.Shadow.PerObjectShadowMapResolution=1024
r.Shadow.PerObjectResolutionMax=2048
r.Shadow.PerObjectResolutionMin=512
;
r.DetailMode=2
r.MaterialQualityLevel=1
r.KuroMaterialQualityLevel=1
r.ViewDistanceScale=2.0
foliage.LODDistanceScale=2.0
foliage.DensityType=2
r.Streaming.MinBoost=2.0
r.SSR.Quality=3
r.SSR.MaxRoughness=0.8
r.SSR.HalfResSceneColor=0
r.LightShaftDownSampleFactor=1
a.URO.ForceAnimRate=1
Kuro.CppEffectSystem.UseLowMemoryPlayerEffectLruCapacity=false
r.Kuro.Foliage.GrassCullDistanceMax=15000
r.Kuro.Foliage.Grass3_0CullDistanceMax=15000
wp.Runtime.SoraGridBlackListHeight=15000
wp.Runtime.PlannedLoadingRangeScale=1.0
r.Streamline.DLSSG.RetainResourcesWhenOff=1
r.RayTracing.LoadConfig=0
;
r.MaxAnisotropy=16
r.FidelityFX.FSR3.Sharpness=0.34
r.FidelityFX.FSR3.EnableAutoReactiveMask=1
r.FidelityFX.FSR3.EnableTCAT=1
r.FidelityFX.FSR3.FrameGeneration.Enable=0
;
fx.Niagara.ForceAutoPooling=1
niagara.CreateShadersOnLoad=0
r.InstanceCulling.OcclusionCull=1
r.AsyncComputePSO=1
D3D12.PSO.DriverOptimizedDiskCache=1
;r.d3d12.pso.diskcache=1
r.D3D12.ResidencyManagement=1
;
r.TemporalAA.Algorithm=2
r.TemporalAA.Upsampling=1
r.TemporalAACurrentFrameWeight=0.15
r.TemporalAAFilterSize=0.8
r.TemporalAASamples=8
;
r.GPUCrashDebugging=0
r.GPUCrashDebugging.Aftermath=0
r.D3D12.DRED=0
r.D3D12.EnableBreadcrumbs=0
r.DebugDisableUiSceneRendering=0
; you need enabled Adaptive-Sync or VRR on your display, otherwise remove folowing two line
r.VSync=0
r.D3D12.UseAllowTearing=1
;
r.Streaming.FullyLoadUsedTextures=0
r.Streaming.PoolSizeForMeshes=2048
r.TextureStreaming.UseBackgroundThreadPool=1
r.TextureStreaming=1
;
r.Streaming.HLODStrategy=2
r.Streaming.UseBackgroundThreadPool=1

[/Script/Engine.GarbageCollectionSettings]
gc.AllowParallelGC=1
gc.CreateGCClusters=1
gc.MultithreadedDestructionEnabled=1

[ConsoleVariables]
r.RayTracing.LoadConfig=0
; you need enabled Adaptive-Sync or VRR on your display, otherwise remove folowing two line
r.VSync=0
r.D3D12.UseAllowTearing=1







